# foe-rbs/frontend/Dockerfile.dev
FROM node:20-alpine
EXPOSE 5173
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# Command to run your Vue dev server (e.g., using Vite)
CMD ["npm", "run", "dev"]