services:
  - type: web
    name: foe-rbs-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /api/health
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
